language: generic
sudo: required
services: 
 - docker 


before_install:
 - docker build -t dokcont -f Dockerfile.dev .  

script: 
 - docker run -e CI=true dokcont npm run test   


deloy:
 provider: elasticbeanstalk
 region: "eu-west-3"
 app: "react-app"
 env: "react-app-env"
 bucket_name: "elasticbeanstalk-eu-west-3-026090555600"
 bucket_path: "react-app"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY 